%YAML:1.0
server:
    url: dev.mirrorworlds.icat.vt.edu
    port: 9999

classes:
    # oncam image size should be 1056x960, but make sure to
    # take cropping into account for spawn regions
    oncam:
        username: admin
        password: admin
        path: video.cgi?.mjpg
    vivotek:
        username: root
        password: admin
        path: video.mjpg

cameras:
    - id: 1
      name: observation
      desc: Observation Room
      class: oncam
      ip: '192.168.1.14'
      crop: [100, 100, 900, 700]
      spawns:
        - [690, 40, 160, 180]

    - id: 2
      name: learningA
      desc: Learning Lab A
      class: oncam
      ip: '192.168.1.15'
      crop: [70, 30, 900, 800]

    - id: 3
      name: learningB
      desc: Learning Lab B
      class: oncam
      ip: '192.168.1.11'
      crop: [130, 260, 800, 550]

    - id: 4
      name: learningC
      desc: Learning Lab C
      class: oncam
      ip: '192.168.1.10'
      crop: [130, 180, 800, 570]

    - id: 5
      name: learningD
      desc: Learning Lab D
      class: oncam
      ip: '192.168.1.12'
      crop: [130, 100, 800, 570]

    - id: 6
      name: hallwayA
      desc: Hallway A
      class: vivotek
      ip: '192.168.1.16'
      crop: [180, 90, 800, 800]

    - id: 7
      name: hallwayB
      desc: Hallway B
      class: vivotek
      ip: '192.168.1.17'
      crop: [180, 240, 750, 650]

    - id: 8
      name: hallwayC
      desc: Hallway C
      class: vivotek
      ip: '192.168.1.18'
      crop: [180, 250, 750, 650]

    - id: 9
      name: hallwayD
      desc: Hallway D
      class: vivotek
      ip: '192.168.1.19'
      crop: [180, 250, 750, 800]

    - id: 10
      name: hallwayE
      desc: Hallway E
      class: vivotek
      ip: '192.168.1.20'
      crop: [180, 250, 750, 726]

    - id: 14
      name: hallwayF
      desc: Hallway F
      class: oncam
      ip: '192.168.1.44'
      crop: [130, 260, 800, 550]

    - id: 15
      name: hallwayG
      desc: Hallway G
      class: oncam
      ip: '192.168.1.45'
      crop: [500, 150, 1100, 700]

    - id: 16
      name: hallwayH
      desc: Hallway H
      class: oncam
      ip: '192.168.1.46'
      crop: [130, 260, 800, 550]

    - id: 17
      name: hallwayI
      desc: Hallway I
      class: oncam
      ip: '192.168.1.47'
      crop: [130, 200, 800, 570]

    - id: 18
      name: hallwayJ
      desc: Hallway J
      class: oncam
      ip: '192.168.1.48'
      crop: [130, 260, 800, 560]

    - id: 19
      name: hallwayK
      desc: Hallway K
      class: vivotek
      ip: '192.168.1.49'
      crop: [180, 150, 750, 650]

    
